### ISSUE TITLE
Codeaon : Make Navbar Responsive

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Codeaon#1]
## Task

- Make the navbar responsive 
- Create a hamburger menu for the navbar dropdown
- Include only the nav list items for the dropdown ( Don't include the `Codeaon` tag )
- Add a small animation to the hamburger menu icon when clicked 

Before contributing read [contributing.md](https://github.com/DSCKGEC/Codeaon/blob/main/contributing.md)

**Comment by vaibhavi-roy** [comment]
Hello @soujo I want to work on this issue.

**Comment by soujo** [comment]
> Hello @soujo I want to work on this issue.

Sure , go ahead

**Comment by soujo** [comment]
@vaibhavi-roy any updates ?
