### ISSUE TITLE
Codeaon : Scroll down animation

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Codeaon#7]
## Task

- Give a scroll down animation in the hero-section of Blog page 
- Apply the animation with or below the `Explore` button
- Reference : https://codepen.io/nxworld/pen/OyRrGy

Before contributing read [contributing.md](https://github.com/DSCKGEC/Codeaon/blob/main/contributing.md)

**Comment by RajavJain** [comment]
Hey, can I work upon it?

**Comment by soujo** [comment]
> Hey, can I work upon it?

Sure , go ahead

**Comment by soujo** [comment]
@RajavJain any updates ? The time interval for this issue is over , its been 3 days
