### ISSUE TITLE
Codeaon : Sign up button animation

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Codeaon#8]
## Task 
- Create an animation when the user hovers on signup button on the navbar
- Reference : https://codepen.io/foxeisen/pen/bqZxLa

Before contributing read [contributing.md](https://github.com/DSCKGEC/Codeaon/blob/main/contributing.md)

**Comment by Harshit-3905** [comment]
I would like to work on this issue .

**Comment by soujo** [comment]
Yes you can start working on it @Harshit-3905

**Comment by soujo** [comment]
@Harshit-3905 Any update ?
